version: '3'
services:
  tp-foyer:
    image: ibtihelerrais/alpine:1.0.0
    ports:
      - "8082:8082"
    networks:
      - app-network
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: tpfoyerdb
    ports:
      - "3306:3306"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
